apiRules:
  - exclude:
      uidRegex: ^Newtonsoft\.Json
      type: Namespace
  - exclude:
      uidRegex: ^System
      type: Namespace
  - exclude:
      uidRegex: Telerik.ReportServer.Services.Models.Obsolete
      type: Namespace
  - exclude:
      uidRegex: Telerik.WebReportDesigner.Services.Models
      type: Namespace
